import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getProject, projects } from "../../content";
import { Footer, Header, PlaceholderBanner, RelatedLinks } from "../../components";

export function generateStaticParams() { return projects.map((project) => ({ slug: project.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const project = getProject(slug); return project ? { title: `${project.title} · Projects`, description: project.description } : {}; }
export default async function ProjectDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const project = getProject(slug); if (!project) notFound(); return <><Header /><main id="main"><article className="detail-article container"><Link className="back-link" href="/projects">← All projects</Link><header className="detail-title"><p className="eyebrow">{project.eyebrow}</p><h1>{project.title}</h1><p>{project.description}</p><div className="detail-labels"><span>{project.status}</span><span>{project.role}</span></div></header><PlaceholderBanner>This is a placeholder case-study framework. Replace every field with verified information or remove it.</PlaceholderBanner><section className="architecture-panel"><div><p className="eyebrow">System flow</p><h2>How the parts connect</h2></div><div className="architecture-flow">{project.systems.map((system, index) => <div key={system}><span>0{index + 1}</span><strong>{system}</strong>{index < project.systems.length - 1 && <i>→</i>}</div>)}</div><p className="diagram-caption">Text description: a sequential example flow through {project.systems.join(", ")}.</p></section><div className="case-grid"><aside><p className="eyebrow">On this page</p><a href="#problem">01 · Problem</a><a href="#constraints">02 · Constraints</a><a href="#decision">03 · Decision</a><a href="#systems">04 · Systems</a><a href="#result">05 · Result</a><a href="#learning">06 · Learning</a></aside><div className="case-content"><section id="problem"><span>01</span><h2>The problem</h2><p>{project.description}</p></section><section id="constraints"><span>02</span><h2>Constraints and responsibility</h2><p>{project.challenge}</p><p>{project.role}</p></section><section id="decision"><span>03</span><h2>The engineering decision</h2><p>{project.approach}</p></section><section id="systems"><span>04</span><h2>Technologies and services connected</h2><div className="tag-row">{project.technologies.map((item) => <span key={item}>{item}</span>)}</div></section><section id="result"><span>05</span><h2>The result</h2><p>{project.outcome}</p></section><section id="learning"><span>06</span><h2>What I learned</h2><p>{project.learning}</p></section></div></div><RelatedLinks writingSlugs={project.relatedWriting} bookSlugs={project.relatedBooks} /></article></main><Footer /></>; }
