import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { books, formatDate, getProject, getWriting, writing } from "../../content";
import { Footer, Header, PlaceholderBanner } from "../../components";

export function generateStaticParams() { return writing.map((item) => ({ slug: item.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = getWriting(slug); return item ? { title: `${item.title} · ${item.type}`, description: item.description, openGraph: { type: "article", publishedTime: item.date, modifiedTime: item.updated } } : {}; }
export default async function WritingDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = getWriting(slug); if (!item) notFound(); const relatedProject = item.relatedProject ? getProject(item.relatedProject) : undefined; const relatedBook = item.relatedBook ? books.find((book) => book.slug === item.relatedBook) : undefined; return <><Header /><main id="main"><article className="reading-article container"><Link className="back-link" href="/writing">← All writing</Link><header><p className="eyebrow">{item.type} / {item.category}</p><h1>{item.title}</h1><p className="article-deck">{item.description}</p><div className="article-meta"><span>Published <time dateTime={item.date}>{formatDate(item.date)}</time></span><span>Updated <time dateTime={item.updated}>{formatDate(item.updated)}</time></span><span>{item.readTime} min read</span></div></header>{item.note && <PlaceholderBanner>{item.note}</PlaceholderBanner>}<div className="article-layout"><aside><p className="eyebrow">Contents</p>{item.sections.map((section, index) => <a key={section.heading} href={`#section-${index + 1}`}>{String(index + 1).padStart(2, "0")} · {section.heading}</a>)}</aside><div className="article-body"><p className="article-disclosure">This page distinguishes a demonstration structure from verified guidance. Replace placeholder statements with facts, experience, references, and explicit uncertainty.</p>{item.sections.map((section, index) => <section key={section.heading} id={`section-${index + 1}`}><p className="eyebrow">Section {String(index + 1).padStart(2, "0")}</p><h2>{section.heading}</h2>{section.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}<div className="references"><h2>References and connections</h2><p>Add primary sources and references used to verify factual claims.</p>{relatedProject && <Link href={`/projects/${relatedProject.slug}`}>Related project · {relatedProject.title} ↗</Link>}{relatedBook && <Link href={`/library/${relatedBook.slug}`}>Related book · {relatedBook.title} ↗</Link>}</div></div></div><nav className="next-record" aria-label="Previous and next article"><Link href={`/writing/${writing[(writing.indexOf(item) - 1 + writing.length) % writing.length].slug}`}>← Previous record</Link><Link href={`/writing/${writing[(writing.indexOf(item) + 1) % writing.length].slug}`}>Next record →</Link></nav></article></main><Footer /></>; }
